#! /usr/bin/env zsh

exec_name=$(basename $0)

# colours
BOLD=$(tput bold)
RED=$(tput setaf 1)
END=$(tput sgr0)

# usage instructions
help(){
    echo "Usage: $exec_name <subcommand> [options]\n"
    echo "Subcommands:"
    echo "    curr   display current project"
    echo "    proj   list available projects"
    echo ""
    echo "For help with each subcommand run:"
    echo "$exec_name <subcommand> -h|--help"
    echo ""
}

# display current project
curr(){
}

# list available projects
proj(){
    echo -ne "${BOLD}${RED}Current projects:${END} \n"
    cat projects.txt
}

subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        help
        ;;
    *)
        shift
        ${subcommand} $@
        if [ $? = 127 ]; then
            echo "Error: '$subcommand' is not a known subcommand." >&2
            echo "       Run '$exec_name --help' for a list of known subcommands." >&2
            exit 1
        fi
        ;;
esac
